<?php

$viewModel = $this->getViewModel();

$films = $viewModel->getAllActiveFilms();

$customerFavouriteFilm = $viewModel->getCustomerFavouriteFilm();

?>

<h1><?= __('Films'); ?></h1>
<?php foreach ($films as $film): ?>
    <p><?= $film->getTitle(); ?></p>
<?php endforeach; ?>
<h1><?= __('Favourite Film'); ?></h1>
<?php var_dump($customerFavouriteFilm); ?>
<p><?= $customerFavouriteFilm; ?> - test</p>
<?php foreach ($films as $film): ?>
    <?php if ($film->getId() == $customerFavouriteFilm): ?>
        <p><?= $film->getTitle(); ?></p>
    <?php endif; ?>
<?php endforeach; ?>
